export interface ActualFab {
  JobNo?: string;
  WorkShopName?: string;
  WorkGroup?: string;
  Weight?: number;
  WeightString?: string;
  PlanMH?: number;
  PlanMHString?: string;
  ActualMH?: number;
  ActualMHString?: string;
  Diff?: number;
  DiffString?: string;
  ProgressMH?: string;
  PlanMHOT?: number;
  PlanMHOTString?: string;
  ActualMHOT?: number;
  ActualMHOTString?: string;
  DiffOT?: number;
  DiffOTString?: string;
  ProgressOTMH?: string;
  PlanKg?: string;
  ActualKg?: string;
  PlanMT?: string;
  ActualMT?: string;
  // Addition
  NormalTime?: number;
  OverTime?: number;
  OverTimeX?: number;
  NormalTimeString?: string;
  OverTimeString?: string;
  OverTimeXString?: string;
  Status?: string;
}
